apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  labels:
    app: payment-processor
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
      - name: processor
        image: payment-processor:latest 
        imagePullPolicy: IfNotPresent 
        env:
        - name: AWS__SQS__QueueUrl
          value: "http://host.docker.internal:4566/000000000000/ProcessamentoPagamento"
        - name: AWS__ServiceURL
          value: "http://host.docker.internal:4566"
        - name: AWS__Region
          value: "us-east-1"